{{- if and .Values.minio.enabled .Values.minio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.project_name }}-minio-pvc
  labels:
    {{- include "minioLabels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.minio.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
  {{- if .Values.minio.persistence.storageClass }}
  storageClassName: {{ .Values.minio.persistence.storageClass }}
  {{- end }}
{{- end }}

